---
site_name: "2026 Webex Contact Center Partner Bootcamp" 
site_description: "Proactive Debt Collection and Contention resolution"
site_author: Luis Garcia Delgado, Juan Corral, Sebastian Hernandez, Stephanie Ross
copyright: Copyright &copy; 2026 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexesmkd
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.follow
    - toc.integrate
   
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/webexLogo91.png
  favicon: template_assets/webex75.png
extra:
  generator: false
  repo: "https://github.com/cx-partner/bootcamp2026"
  site_event: test
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - template_assets/js/newLoad.js
  - template_assets/js/setInfo.js
plugins:
  - search
  
  # - with-pdf:
  #     cover_title: LABXXX-1234
  #     cover_subtitle: My famous WebexOne Lab
  #     cover_logo: template_assets/Wx1_25_PDF_image.jpg
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true  # Makes them look much better (Material style)
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true    
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.keys
  - toc:
      permalink: true
      toc_depth: 3

  

nav:
  - Home: index.md
  - Readme:
      - 2026 WxCC Bootcamp: overview.md
  - Pre-requisites: 
    - Email Digital Channel: pre_req_email_channel.md
    - Airtable Base: pre_req_airtable.md
  - Labs:
    - Lab 1 - Proactive Outbound Reach: lab1_campaign_manager.md
    - Lab 2 - Automated Debt collection: lab2_debt_ai_agent.md
    - Lab 3 - Human escalation & RT Assist: lab3_human_ai_assist.md
    - Lab 4 - Cross-skill multi-agent orchestration: lab4_ai_agent_transfer.md
    - Lab extra - NovaPay payment service: lab_novapay.md

  - How to use this guide:
      - Setting up and using the tool:
        - Initial Setup: howToUse/initialSetup.md
        - Using the tool after the initial setup: howToUse/postInitial.md
        - Publishing your changes: howToUse/syncChanges.md
      - Styling and Advanced Features:
        - Markdown and Other References: howToUse/references.md
        - Custom Features: howToUse/customFeatures.md
        - Custom Admonitions: howToUse/admonition.md

  - Webex Bank Rewards Program: ./bcamp_files/Webex_Bank_Rewards_Program.md